version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: harmonia
      POSTGRES_USER: harmonia-admin
      POSTGRES_PASSWORD: harmonia-admin